const table_with_valid_columns = [
    `submission_uuid`,
    `ptracker_id`
    `facility_code`
    `facility_name`
    `type`
    `visit_date`
    `visit_date_recorded_odk`
    `openmrs_person`
    `openmrs_patient`
    `facility_uuid`
    `given`
    `middle`
    `family`
    `sex`
    `dob`
    `age`
    `country`
    `country_other`
    `district`
    `address`
    `location`
    `phone_number`
    `kin_name`
    `kin_contact`
    // anc part
    `anc_first_hiv_test_status`
    `anc_gravida`
    `anc_para`
    `anc_edd`
    `anc_edd_calculated`
    `anc_lnmp`
    `next_visit_date`
    `next_visit_date_missing`
    `next_facility_to_visit`
    `next_facility_to_visit_transfered`
    `next_facility_to_visit_transfered_other`
    // hiv status part
    `hiv_test_status`
    `hiv_test_result`
    `art_int_status`
    `anc_art_initation`
    `art_int_status_refused_reason`
    `art_int_status_refused_reason_missing`
    `art_number`
    `art_number_missing`
    `art_start_date`
    `art_start_date_missing`
    `vl_test_done`
    `vl_test_date`
    `vl_test_date_missing`
    `vl_test_result`
    `vl_test_result_value`
    `vl_test_result_value_missing`
    // partner testing
    `partner_hivtest_done`
    `partner_hivtest_date`
    `partner_hivtest_date_missing`
    `partner_hivtest_result`
    // MISC
    `provider_uuid`
    `username`
    `submission_date`
    `review_state`
]