
--CREATING INFANT PNC STAGING TABLE--
DROP TABLE IF EXISTS `stag_odk_pnc_infant`;

CREATE TABLE stag_odk_pnc_infant(

  `ptracker_id` varchar(255) DEFAULT NULL,
  `facility_code` varchar(255) DEFAULT NULL,
  `facility_name` varchar(255) DEFAULT NULL,
  `type` varchar(3) NOT NULL DEFAULT '',
  `visit_date` varchar(19) DEFAULT NULL,
  `visit_date_recorded_odk` varchar(19) DEFAULT NULL,
  `openmrs_id` binary(0) DEFAULT NULL,
  `openmrs_person_uuid` varchar(255) DEFAULT NULL,
  `openmrs_patient_uuid` varchar(255) DEFAULT NULL,
  `facility_uuid` varchar(255) DEFAULT NULL,
  `odk_uuid` varchar(80) NOT NULL DEFAULT '',
  `given` varchar(255) DEFAULT NULL,
  `middle` varchar(255) DEFAULT NULL,
  `family` varchar(255) DEFAULT NULL,
  `sex` varchar(255) DEFAULT NULL,
  `dob` varchar(19) DEFAULT NULL,
  `age` int(11) DEFAULT NULL,
  `country` varchar(255) DEFAULT NULL,
  `country_other` varchar(255) DEFAULT NULL,
  `district` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `phone_number` varchar(255) DEFAULT NULL,
  `kin_name` varchar(255) DEFAULT NULL,
  `kin_contact` varchar(255) DEFAULT NULL,
  -- INFANT PNC PART -- 
  'infant_transfer_status' varchar(255) DEFAULT NULL,
  'infant_breastfeeding_status' varchar(255) DEFAULT NULL,
  'infant_transfer_out' varchar(255) DEFAULT NULL,
  'infant_transfer_out_other' varchar(255) DEFAULT NULL,
  'infant_transfer_out_date' varchar(255) DEFAULT NULL,
  'infant_transfer_out_date_missing' varchar(255) DEFAULT NULL,
  'infant_transferin' varchar(255) DEFAULT NULL,
  'infant_transferin_other' varchar(255) DEFAULT NULL,
  'infant_transferin_date' varchar(255) DEFAULT NULL,
  'infant_transferin_date_missing' varchar(255) DEFAULT NULL,
  'infant_next_visit_date' varchar(255) DEFAULT NULL, 
  'infant_next_visit_date_missing' varchar(255) DEFAULT NULL, 
  'infant_event_date' varchar(255) DEFAULT NULL,
  'infant_event_date_missing' varchar(255) DEFAULT NULL,
  'infant_transferto_artclinic_date' varchar(255) DEFAULT NULL,
  'infant_transferto_artclinic_date_missing' varchar(255) DEFAULT NULL,
  'infant_transferto_artclinic' varchar(255) DEFAULT NULL,
  'infant_transferto_artclinic_missing' varchar(255) DEFAULT NULL,
  'hiv_exposure_status' varchar(255) DEFAULT NULL,
  'arv_prophylaxis_status' varchar(255) DEFAULT NULL,
  'arv_prophylaxis_adherence' varchar(255) DEFAULT NULL,
  'ctx_prophylaxis_status' varchar(255) DEFAULT NULL,
  'ctx_prophylaxis_adherence' varchar(255) DEFAULT NULL,
  'infant_hiv_tested' varchar(255) DEFAULT NULL,
  'infant_hiv_test_used' varchar(255) DEFAULT NULL,
  'infant_hiv_test_result' varchar(255) DEFAULT NULL,
  'infant_hiv_test_result_pcr' varchar(255) DEFAULT NULL,
  'infant_hiv_test_conf' varchar(255) DEFAULT NULL,
  'infant_hiv_test_conf_result' varchar(255) DEFAULT NULL,
  'infant_art_linked' varchar(255) DEFAULT NULL, 
  'art_number' varchar(255) DEFAULT NULL,
  'art_number_missing' varchar(255) DEFAULT NULL,
  'infant_date_death' varchar(255) DEFAULT NULL,  
  'infant_date_death_mising' varchar(255) DEFAULT NULL, 
  'parent_ptracker_id' varchar(255) DEFAULT NULL,
   -- MISC --
  `provider_uuid` varchar(255)  NULL,
  `username` varchar(255)  NULL,
  `submission_date` varchar(255) NULL

);
