
--CREATING  LABOUR & DELIVERY STAGING TABLE--
DROP TABLE IF EXISTS `stag_odk_pnc_mother`;

CREATE TABLE stag_odk_delivery(
  `submission_uuid` varchar(255)  NOT NULL PRIMARY KEY,
  `ptracker_id` varchar(255)  NULL,
  `facility_code` varchar(255)  NULL,
  `facility_name` varchar(255)  NULL,
  `type` varchar(3) NOT NULL  ,
  `visit_date` varchar(19)  NULL,
  `visit_date_recorded_odk` varchar(19) DEFAULT NULL,
  `openmrs_id` binary(0)  NULL,
  `openmrs_person_uuid` varchar(255)  NULL,
  `openmrs_patient_uuid` varchar(255)  NULL,
  `facility_uuid` varchar(255)  NULL,
  `odk_uuid` varchar(80) NOT NULL  ,
  `given` varchar(255)  NULL,
  `middle` varchar(255)  NULL,
  `family` varchar(255)  NULL,
  `sex` varchar(255)  NULL,
  `dob` varchar(19)  NULL,
  `age` int(11)  NULL,
  `country` varchar(255)  NULL,
  `country_other` varchar(255)  NULL,
  `district` varchar(255)  NULL,
  `address` varchar(255)  NULL,
  `location` varchar(255)  NULL,
  `phone_number` varchar(255)  NULL,
  `kin_name` varchar(255)  NULL,
  `kin_contact` varchar(255)  NULL,
  -- Mother L&D PART -- 
  `ld_has_pinkbook`  varchar(255)  NULL,
  `ld_motherstatus`  varchar(255)  NULL,
  `ld_discharge_date`  varchar(255)  NULL,
  `ld_discharge_date_missing`  varchar(255)  NULL,
  `ld_numberof_infants`  varchar(255)  NULL,
  `ld_motherstatus_transfered`  varchar(255)  NULL,
  `ld_motherstatus_transfered_other`  varchar(255)  NULL,
  -- HIV STATUS PART -- 
  `anc_first_hiv_test_status`  varchar(255)  NULL,
  `hiv_test_status`  varchar(255)  NULL,
  `hiv_retest_status`  varchar(255)  NULL,
  `hiv_test_result`  varchar(255)  NULL,
  `art_int_status`  varchar(255)  NULL,
  `anc_art_initation`  varchar(255)  NULL,
  `art_int_status_refused_reason`  varchar(255)  NULL,
  `art_int_status_refused_reason_missing`  varchar(255)  NULL,
  `art_number`  varchar(255)  NULL,
  `art_number_missing`  varchar(255)  NULL,
  `art_start_date`  varchar(255)  NULL,
  `vl_test_done`  varchar(255)  NULL,
  `vl_test_date`  varchar(255)  NULL,
  `vl_test_result` varchar(255)  NULL,
  `vl_test_result_value`  varchar(255)  NULL,
   -- MISC --
  `provider_uuid` varchar(255)  NULL,
  `username` varchar(255)  NULL,
  `submission_date` varchar(255) NULL
);
